In [1]:
import torch

In [2]:
x = torch.arange(12)
x

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [4]:
xx = torch.Tensor([[x,x**2,x**3] for x in range(12)])
xx

tensor([[0.0000e+00, 0.0000e+00, 0.0000e+00],
        [1.0000e+00, 1.0000e+00, 1.0000e+00],
        [2.0000e+00, 4.0000e+00, 8.0000e+00],
        [3.0000e+00, 9.0000e+00, 2.7000e+01],
        [4.0000e+00, 1.6000e+01, 6.4000e+01],
        [5.0000e+00, 2.5000e+01, 1.2500e+02],
        [6.0000e+00, 3.6000e+01, 2.1600e+02],
        [7.0000e+00, 4.9000e+01, 3.4300e+02],
        [8.0000e+00, 6.4000e+01, 5.1200e+02],
        [9.0000e+00, 8.1000e+01, 7.2900e+02],
        [1.0000e+01, 1.0000e+02, 1.0000e+03],
        [1.1000e+01, 1.2100e+02, 1.3310e+03]])

In [6]:
torch.Tensor([1])

tensor([1.])

In [7]:
xx.shape

torch.Size([12, 3])

In [8]:
x.device

device(type='cpu')

In [10]:
x.view((2,-1,2)).shape # Возврашает новый  тензор, но новый тензор менятся если меняем старый. 
#Он работает если данных располягаются в одом област память 

torch.Size([2, 3, 2])

In [11]:
x.reshape((2,-1,2)).shape # Esli nuxno kopiq nado clone 

torch.Size([2, 3, 2])

In [12]:
x.reshape((2,-1,2))

tensor([[[ 0,  1],
         [ 2,  3],
         [ 4,  5]],

        [[ 6,  7],
         [ 8,  9],
         [10, 11]]])

In [14]:
x.view((2,-1,2))

tensor([[[ 0,  1],
         [ 2,  3],
         [ 4,  5]],

        [[ 6,  7],
         [ 8,  9],
         [10, 11]]])

In [15]:
x = torch.arange(12).reshape((3,4))
y = torch.tensor([[2,1,4,3],[1,2,3,4],[4,3,2,1]])
torch.mm(x,y.T)

tensor([[ 18,  20,  10],
        [ 58,  60,  50],
        [ 98, 100,  90]])

In [19]:
x,y

(tensor([[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11]]),
 tensor([[2, 1, 4, 3],
         [1, 2, 3, 4],
         [4, 3, 2, 1]]))

In [20]:
torch.cat((x,y),axis=0)

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [ 2,  1,  4,  3],
        [ 1,  2,  3,  4],
        [ 4,  3,  2,  1]])

In [21]:
torch.cat((x,y),axis=1)


tensor([[ 0,  1,  2,  3,  2,  1,  4,  3],
        [ 4,  5,  6,  7,  1,  2,  3,  4],
        [ 8,  9, 10, 11,  4,  3,  2,  1]])

In [25]:
(x<=y).int()

tensor([[1, 1, 1, 1],
        [0, 0, 0, 0],
        [0, 0, 0, 0]], dtype=torch.int32)

In [22]:
x.sum()

tensor(66)

In [26]:
x.sum(dim=1)

tensor([ 6, 22, 38])

In [27]:
x.sum(dim=1,keepdim=True)

tensor([[ 6],
        [22],
        [38]])

In [28]:
x.sum(dim=0,keepdim=True)

tensor([[12, 15, 18, 21]])

In [31]:
x

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])

In [30]:
x.unsqueeze(1)

tensor([[[ 0,  1,  2,  3]],

        [[ 4,  5,  6,  7]],

        [[ 8,  9, 10, 11]]])

In [32]:
x.unsqueeze(2)

tensor([[[ 0],
         [ 1],
         [ 2],
         [ 3]],

        [[ 4],
         [ 5],
         [ 6],
         [ 7]],

        [[ 8],
         [ 9],
         [10],
         [11]]])

In [33]:
x.unsqueeze(2).squeeze()

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])

In [34]:
x.T

tensor([[ 0,  4,  8],
        [ 1,  5,  9],
        [ 2,  6, 10],
        [ 3,  7, 11]])

In [35]:
x.permute(1,0)

tensor([[ 0,  4,  8],
        [ 1,  5,  9],
        [ 2,  6, 10],
        [ 3,  7, 11]])

In [36]:
xx = torch.rand((2,3,4))

In [37]:
xx

tensor([[[0.4130, 0.0448, 0.9682, 0.9225],
         [0.3544, 0.3248, 0.7380, 0.0840],
         [0.5644, 0.8478, 0.2578, 0.6520]],

        [[0.3574, 0.4506, 0.1004, 0.1314],
         [0.3669, 0.5940, 0.0162, 0.6527],
         [0.4958, 0.2843, 0.1285, 0.0805]]])

In [38]:
xx.permute(1,2,0)

tensor([[[0.4130, 0.3574],
         [0.0448, 0.4506],
         [0.9682, 0.1004],
         [0.9225, 0.1314]],

        [[0.3544, 0.3669],
         [0.3248, 0.5940],
         [0.7380, 0.0162],
         [0.0840, 0.6527]],

        [[0.5644, 0.4958],
         [0.8478, 0.2843],
         [0.2578, 0.1285],
         [0.6520, 0.0805]]])

# Broadcast

In [43]:
a = torch.arange(3).reshape((3,1))

In [44]:
a

tensor([[0],
        [1],
        [2]])

In [45]:
b = torch.arange(4).reshape((1,4))

In [46]:
b

tensor([[0, 1, 2, 3]])

In [47]:
a+b

tensor([[0, 1, 2, 3],
        [1, 2, 3, 4],
        [2, 3, 4, 5]])

In [52]:
x

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])

In [59]:
x[1:3,1:3]

tensor([[ 5,  6],
        [ 9, 10]])

In [61]:
x[1:3,1:3] = 9

In [62]:
x

tensor([[ 0,  1,  2,  3],
        [ 4,  9,  9,  7],
        [ 8,  9,  9, 11]])

In [63]:
x[1:3,:] = 9

In [64]:
x

tensor([[0, 1, 2, 3],
        [9, 9, 9, 9],
        [9, 9, 9, 9]])

In [66]:
y = x.numpy()


In [67]:
y = torch.tensor(y)

In [68]:
y

tensor([[0, 1, 2, 3],
        [9, 9, 9, 9],
        [9, 9, 9, 9]])